[config]

# [templates.hyprland]
# input_path = '~/.config/matugen/templates/hyprland-colors.conf'
# output_path = '~/.config/hypr/colors.conf'
# post_hook = 'hyprctl reload'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

# [templates.pywalfox]
# input_path = '~/.config/matugen/templates/pywalfox-colors.json'
# output_path = '~/.cache/wal/colors.json'

[templates.wlogout]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/wlogout/colors.css'

[templates.sequences]
input_path = '~/.config/matugen/templates/sequences'
output_path = '~/.cache/wal/sequences'

# [templates.primary]
# input_path = '~/.config/matugen/templates/primary'
# output_path = '~/.config/ml4w/colors/primary'

# [templates.secondary]
# input_path = '~/.config/matugen/templates/secondary'
# output_path = '~/.config/ml4w/colors/secondary'

# [templates.on_surface]
# input_path = '~/.config/matugen/templates/onsurface'
# output_path = '~/.config/ml4w/colors/onsurface'

[templates.ohmyposh]
input_path = '~/.config/matugen/templates/ohmyposh-colors.json'
output_path = '~/.config/ohmyposh/colors.json'
# post_hook = "jq --slurpfile palette ~/.config/ohmyposh/colors.json '. + $palette[0]' ~/.config/ohmyposh/EDM115-newline.omp.json > /tmp/new_theme.json && mv /tmp/new_theme.json ~/.config/ohmyposh/EDM115-newline.omp.json"
